In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

Clustering- Divide the universities in to groups

In [3]:
Univ=pd.read_csv("Universities.csv")
Univ

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [4]:
Univ.describe()

               SAT       Top10     Accept   SFRatio      Expenses   GradRate
count    25.000000   25.000000  25.000000  25.00000     25.000000  25.000000
mean   1266.440000   76.480000  39.200000  12.72000  27388.000000  86.720000
std     108.359771   19.433905  19.727308   4.06735  14424.883165   9.057778
min    1005.000000   28.000000  14.000000   6.00000   8704.000000  67.000000
25%    1240.000000   74.000000  24.000000  11.00000  15140.000000  81.000000
50%    1285.000000   81.000000  36.000000  12.00000  27553.000000  90.000000
75%    1340.000000   90.000000  50.000000  14.00000  34870.000000  94.000000
max    1415.000000  100.000000  90.000000  25.00000  63575.000000  97.000000

In [5]:
#read all numeric columns in to Univ1
Univ1=Univ.iloc[:,1:]

In [6]:
cols=Univ1.columns

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaled_Univ_df=pd.DataFrame(scaler.fit_transform(Univ1),columns=cols)
scaled_Univ_df

         SAT     Top10    Accept   SFRatio  Expenses  GradRate
0   0.410284  0.657519 -0.889867  0.070260 -0.331413  0.820303
1   1.399259  1.235212 -0.734657 -1.686251  2.560381 -0.644524
2  -0.060657 -0.760454  1.024382 -0.933460 -0.167121 -1.658634
3   0.410284 -0.025208 -0.786394 -0.180670  0.291649  0.144229
4   0.127719  0.342414 -0.320766  0.070260 -0.390846  0.369587
5   0.692848  0.657519 -0.838130 -0.682530  0.337780  0.932982
6   0.457378  0.710037 -0.475975 -0.180670  0.296955  0.932982
7  -0.107751 -0.130243 -0.786394 -0.180670 -0.513817  0.594945
8   1.257977  0.762555 -1.303758 -0.431600  0.858743  1.158339
9   0.363190 -0.077726  0.248335 -1.435321  2.214818  0.031550
10  1.069601  0.920107 -0.475975 -0.682530  0.529383  0.482266
11 -0.060657  0.447449 -0.010347 -0.431600  0.046981  0.256908
12 -0.107751  0.237379  0.144862  0.070260 -0.867871  0.820303
13 -1.746625 -2.020875  0.765699  1.324911 -1.217184 -0.757202
14  1.022507  0.762555 -1.303758 -1.184390  0.200376  0.932982
15 -2.462455 -2.546050  2.628211  1.575841 -1.296358 -1.996671
16  0.881224  0.710037 -0.993340 -0.180670  0.641174  0.707624
17 -1.803138 -1.443182  1.438273  3.081422 -1.321971 -2.222029
18 -0.249033  0.972625  0.041389  1.073981 -0.866597 -0.982560
19  0.221907 -0.077726  0.558754  0.070260  0.777730  0.031550
20 -0.814162 -0.602901  1.490010  0.823051 -0.843248 -0.193808
21  0.174813  0.184862 -0.165557 -0.431600  0.011674  0.369587
22 -0.390316  0.027309  0.248335  0.321191 -0.993318  0.594945
23 -1.708950 -1.915840  1.541746  0.572121 -1.098883 -1.771313
24  1.022507  0.972625 -1.045076 -0.431600  1.140982  1.045661

In [8]:
from sklearn.cluster import KMeans
clusters_new=KMeans(3,random_state=0)
clusters_new.fit(scaled_Univ_df)

C:\Users\bicha\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Users\bicha\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\bicha\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bicha\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\bicha\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
C:\Users\bicha\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(n_clusters=3, random_state=0)

In [9]:
set(clusters_new.labels_)

{0, 1, 2}

In [12]:
Univ['clusterid_new']=clusters_new.labels_

In [16]:
Univ

,Univ,SAT,Top10,Accept,SFRatio,Expenses,GradRate,clusterid_new
0,Brown,1310,89,22,13,22704,94,1
1,CalTech,1415,100,25,6,63575,81,2
2,CMU,1260,62,59,9,25026,72,1
3,Columbia,1310,76,24,12,31510,88,1
4,Cornell,1280,83,33,13,21864,90,1
5,Dartmouth,1340,89,23,10,32162,95,1
6,Duke,1315,90,30,12,31585,95,1
7,Georgetown,1255,74,24,12,20126,92,1
8,Harvard,1400,91,14,11,39525,97,1
9,JohnsHopkins,1305,75,44,7,58691,87,2
10,MIT,1380,94,30,10,34870,91,1
11,Northwestern,1260,85,39,11,28052,89,1
12,NotreDame,1255,81,42,13,15122,94,1
13,PennState,1081,38,54,18,10185,80,0
14,Princeton,1375,91,14,8,30220,95,1
15,Purdue,1005,28,90,19,9066,69,0
16,Stanford,1360,90,20,12,36450,93,1
17,TexasA&M,1075,49,67,25,8704,67,0
18,UCBerkeley,1240,95,40,17,15140,78,1
19,UChicago,1290,75,50,13,38380,87,1
20,UMichigan,1180,65,68,16,15470,85,0
21,UPenn,1285,80,36,11,27553,90,1
22,UVA,1225,77,44,14,13349,92,1
23,UWisconsin,1085,40,69,15,11857,71,0
24,Yale,1375,95,19,11,43514,96,1

Observations:
 - Custer 2 appears to be top reted universities cluster as the cut off score, Top 10,SFRatio parameter mean values are highest
 - Cluster 1 appears to occupy the middle level rater

In [18]:
Univ[Univ['clusterid_new']==0]

,Univ,SAT,Top10,Accept,SFRatio,Expenses,GradRate,clusterid_new
13,PennState,1081,38,54,18,10185,80,0
15,Purdue,1005,28,90,19,9066,69,0
17,TexasA&M,1075,49,67,25,8704,67,0
20,UMichigan,1180,65,68,16,15470,85,0
23,UWisconsin,1085,40,69,15,11857,71,0